version: "3"
services:
  postgres-db:
    image: postgres:14
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - rag-net
  server:
    build:
      context: .
    ports:
      - 8300:8300
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres-db:5432/example
      - DATA_URL=thiomajid/clarins-test
    depends_on:
      - postgres-db
    networks:
      - rag-net
volumes:
  db-data:
networks:
  rag-net:
    driver: bridge
