version: "0.1"
services:
  db:
    image: postgres:14
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - default
    # healthcheck:
    #   test: ["CMD", "pg_isready"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
  server:
    build:
      context: .
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/example
      - DATA_URL=thiomajid/clarins-test
    depends_on:
      - db
    networks:
      - default
volumes:
  db-data:
