version: "0.1"
services:
  db:
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - rag-net
    ports:
      - "5432:5432"
  server:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/example
      - DATA_URL=thiomajid/clarins-test
    depends_on:
      - db
    networks:
      - rag-net
volumes:
  db-data:
networks:
  rag-net:
    driver: bridge
